# Generated by Django 5.0.4 on 2024-04-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=60)),
                ('Correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
    ]
