# Generated by Django 5.0.4 on 2024-04-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaciones',
            old_name='telefono',
            new_name='Telefono',
        ),
        migrations.AddField(
            model_name='reservaciones',
            name='FechaReserva',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservaciones',
            name='NoPersonas',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
