# Generated by Django 5.0.4 on 2024-05-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0003_reservaciones_horareserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaciones',
            name='codigo_unico',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
