# Generated by Django 5.0.4 on 2024-04-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePlato', models.CharField(max_length=45)),
                ('Descripcion', models.CharField(max_length=60)),
                ('TiempoPreparación', models.CharField(max_length=45)),
                ('Precio', models.FloatField(max_length=55)),
            ],
        ),
    ]
